# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 19:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_auto_20170207_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='neighborhood',
            field=models.CharField(choices=[('1', 'downtown'), ('2', 'plateau'), ('3', 'westmount')], max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(choices=[('1', 'undergraduate'), ('2', 'graduate'), ('3', 'faculty'), ('4', 'other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
