# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0017_auto_20170215_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='adress',
            new_name='address',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address_display',
            field=models.CharField(default='', max_length=60),
        ),
    ]
