# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0023_remove_tracks_artist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.CharField(choices=[(b'1', b'under 20'), (b'2', b'20-25'), (b'3', b'26-30'), (b'4', b'31-40'), (b'5', b'over 40')], max_length=30),
        ),
    ]
