# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0025_auto_20170302_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracks',
            name='track_pseudo',
            field=models.CharField(default=b'', max_length=50),
        ),
    ]
