# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0033_traj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.CharField(default=b'', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='area',
            field=models.CharField(default=b'', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.CharField(default=b'', max_length=30),
        ),
    ]
