# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0034_auto_20170317_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(default=b'', max_length=30),
        ),
    ]
