# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0036_tracks_featuring'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracks',
            name='acousticness',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tracks',
            name='danceability',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tracks',
            name='energy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tracks',
            name='instrumentalness',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tracks',
            name='key',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tracks',
            name='liveness',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tracks',
            name='loudness',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tracks',
            name='speechiness',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tracks',
            name='tempo',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tracks',
            name='time_signature',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tracks',
            name='valence',
            field=models.FloatField(default=0),
        ),
    ]
