# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0038_auto_20170413_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='key_traj',
            field=models.ManyToManyField(to='log.Traj'),
        ),
        migrations.AddField(
            model_name='traj',
            name='key',
            field=models.CharField(default=b'', max_length=50),
        ),
    ]
