# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 15:44
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields
import log.models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0039_auto_20170413_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='key_traj',
        ),
        migrations.AddField(
            model_name='history',
            name='key_traj',
            field=jsonfield.fields.JSONField(default=log.models.my_default),
        ),
    ]
