# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import log.models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0040_auto_20170413_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traj',
            name='key',
            field=models.CharField(default=log.models.my_default, max_length=50),
        ),
    ]
