# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0041_auto_20170413_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='Album_name',
            field=models.CharField(default=b'', max_length=250),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='Artist',
            field=models.CharField(default=b'', max_length=250),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='featuring',
            field=models.CharField(blank=True, default=b'', max_length=250),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='track_genre',
            field=models.CharField(default=b'pop', max_length=250),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='track_link',
            field=models.CharField(default=b'', max_length=250),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='track_name',
            field=models.CharField(default=b'', max_length=250),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='track_pseudo',
            field=models.CharField(default=b'', max_length=250),
        ),
        migrations.AlterField(
            model_name='traj',
            name='key',
            field=models.CharField(default=b'', max_length=50),
        ),
    ]
