# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0043_history_novelty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coments',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='coments',
            name='user',
        ),
        migrations.DeleteModel(
            name='Coments',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
