# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 15:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0011_auto_20170208_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('1', '1.0'), ('2', '1.5'), ('3', '2.0'), ('4', '2.5'), ('5', '3.0'), ('6', '3.5'), ('7', '4.0'), ('8', '4.5'), ('9', '5.0')], max_length=3)),
                ('review', models.CharField(default='', max_length=300)),
                ('Restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
