# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0012_coments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coments',
            old_name='Restaurant',
            new_name='restaurant',
        ),
    ]
