# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0013_auto_20170212_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='coments',
            name='restaurant_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
