# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 19:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20170207_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='neighborhood',
            field=models.CharField(choices=[('1', 'America'), ('2', 'Europe'), ('3', 'Asia')], max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(choices=[('1', 'America'), ('2', 'Europe'), ('3', 'Asia')], max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.CharField(choices=[('1', 'America'), ('2', 'Europe'), ('3', 'Asia')], max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
