# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0008_auto_20170207_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='biz_hours',
            field=models.CharField(max_length=10000),
        ),
    ]
