# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0010_auto_20170208_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='pseudo',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
