# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0014_coments_restaurant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='nb_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='nb_rating_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='nb_rating_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='nb_rating_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='nb_rating_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='nb_rating_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coments',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=3),
        ),
    ]
