# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0015_auto_20170212_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='morning_day0_end',
            field=models.CharField(default='Closed', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='morning_day0_start',
            field=models.CharField(default='Closed', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='morning_day1_end',
            field=models.CharField(default='Closed', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='morning_day1_start',
            field=models.CharField(default='Closed', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='morning_day2_end',
            field=models.CharField(default='Closed', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='morning_day2_start',
            field=models.CharField(default='Closed', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='morning_day3_start',
            field=models.CharField(default='Closed', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='morning_day4_end',
            field=models.CharField(default='Closed', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='morning_day4_start',
            field=models.CharField(default='Closed', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='morning_day5_end',
            field=models.CharField(default='Closed', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='morning_day5_start',
            field=models.CharField(default='Closed', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='morning_day6_end',
            field=models.CharField(default='Closed', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='morning_day7_end',
            field=models.CharField(default='Closed', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='morning_day7_start',
            field=models.CharField(default='Closed', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='mornings_day3_end',
            field=models.CharField(default='Closed', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='mornings_day6_start',
            field=models.CharField(default='Closed', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='night_day0_end',
            field=models.CharField(default='Closed', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='night_day0_start',
            field=models.CharField(default='Closed', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='night_day1_end',
            field=models.CharField(default='Closed', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='night_day1_start',
            field=models.CharField(default='Closed', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='night_day2_end',
            field=models.CharField(default='Closed', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='night_day2_start',
            field=models.CharField(default='Closed', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='night_day3_start',
            field=models.CharField(default='Closed', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='night_day4_end',
            field=models.CharField(default='Closed', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='night_day4_start',
            field=models.CharField(default='Closed', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='night_day5_end',
            field=models.CharField(default='Closed', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='night_day5_start',
            field=models.CharField(default='Closed', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='night_day6_end',
            field=models.CharField(default='Closed', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='night_day7_end',
            field=models.CharField(default='Closed', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='night_day7_start',
            field=models.CharField(default='Closed', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='nights_day3_end',
            field=models.CharField(default='Closed', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='nights_day6_start',
            field=models.CharField(default='Closed', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='price_range_display',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='state',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='price_coments',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='price_range',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='type_of_food',
            field=models.CharField(default='', max_length=50),
        ),
    ]
