# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0018_auto_20170215_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='morning_day7_end',
            new_name='morning_day3_end',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='morning_day7_start',
            new_name='morning_day6_start',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='mornings_day3_end',
            new_name='night_day3_end',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='mornings_day6_start',
            new_name='night_day6_start',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='night_day7_end',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='night_day7_start',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='nights_day3_end',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='nights_day6_start',
        ),
    ]
