# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-01 22:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0019_auto_20170215_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track_Coments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[(b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4'), (b'5', b'5')], max_length=6)),
                ('wordcloud', models.CharField(default=b'', max_length=250)),
                ('time', models.CharField(default=b'', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(default=b'', max_length=50)),
                ('track_popularity', models.FloatField(default=0)),
                ('track_genre', models.CharField(default=b'', max_length=250)),
                ('Artist', models.CharField(default=b'', max_length=50)),
                ('Artist_image', models.URLField(blank=True)),
                ('Artist_popularity', models.FloatField(default=0)),
                ('Artist_genre', models.CharField(default=b'', max_length=50)),
                ('Album_name', models.CharField(default=b'', max_length=50)),
                ('Album_cover', models.URLField(blank=True)),
                ('lyrics', models.CharField(default=b'', max_length=250)),
                ('duration', models.FloatField(default=0)),
                ('preview', models.URLField(blank=True)),
                ('wordcloud', models.CharField(default=b'', max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='occupation',
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.CharField(choices=[(b'1', b'under 20'), (b'2', b'20-25'), (b'3', b'25-30'), (b'4', b'30-40'), (b'5', b'over 40')], default='1', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='area',
            field=models.CharField(choices=[(b'\t1\t', b'\tArts & Humanities\t'), (b'\t2\t', b'\tEngineering & Technology\t'), (b'\t3\t', b'\tLife Sciences & Medicine\t'), (b'\t4\t', b'\tNatural Sciences\t'), (b'\t5\t', b'\tSocial Sciences & Management\t')], default='1', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track_coments',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Tracks'),
        ),
        migrations.AddField(
            model_name='track_coments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
