# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0024_auto_20170302_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track_coments',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
