# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0026_tracks_track_pseudo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracks',
            old_name='Artist_genre',
            new_name='track_link',
        ),
        migrations.RemoveField(
            model_name='tracks',
            name='lyrics',
        ),
        migrations.RemoveField(
            model_name='tracks',
            name='wordcloud',
        ),
        migrations.AlterField(
            model_name='tracks',
            name='track_genre',
            field=models.CharField(default=b'pop', max_length=50),
        ),
    ]
