# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0027_auto_20170305_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracks',
            name='nb_rate',
            field=models.IntegerField(default=1),
        ),
    ]
