# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0028_tracks_nb_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracks',
            old_name='nb_rate',
            new_name='nb_rating',
        ),
    ]
