# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_auto_20170207_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('site_web', models.URLField(blank=True)),
                ('main_photos', models.URLField(blank=True)),
                ('photos_url', models.URLField(blank=True)),
                ('type_of_food', models.CharField(max_length=50)),
                ('nb_reviews', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('price_range', models.CharField(max_length=15)),
                ('price_coments', models.CharField(max_length=15)),
                ('adress', models.CharField(max_length=40)),
                ('postal_code', models.CharField(blank=True, max_length=7, null=True)),
                ('neighborhood', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('longitude', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('biz_hours', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(choices=[(1, 'undergraduate student'), (2, 'graduate student'), (3, 'faculty'), (4, 'other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.CharField(choices=[(1, 'North America'), (2, 'South America'), (3, 'Central America'), (4, 'Northern Europe'), (5, 'Europe'), (6, 'Eastern Europe'), (8, 'Oceania'), (9, 'Asia'), (10, 'Southeast Asia'), (11, 'Middle East'), (12, 'North Africa'), (13, 'Southern Africa')], max_length=30),
        ),
    ]
