# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0016_auto_20170215_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='country',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='biz_hours',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
